export SDM_HOME="${HOME}/projects/sdm/dm"

export SDM_MOBI_URL=mobi-ctrol-api-dev.spoud.io:443
export SDM_SPOUD_URL=spoud-ctrol-api-dev.spoud.io:443

export SDM_CODEC_ENCRYPTION_ENABLED=false
export SDM_CONTROL_CONNECTION_URL=${SDM_MOBI_URL}
export SDM_CONTROL_CONNECTION_AUTHORIZATION=${SDM_AUTH}
export SDM_CONTROL_CONNECTION_CLUSTER="dev-3"

export SDM_TRANSPORT_CONNECTION_URL=${SDM_CONTROL_CONNECTION_URL}
export SDM_TRANSPORT_CONNECTION_AUTHORIZATION=${SDM_CONTROL_CONNECTION_AUTHORIZATION}
export SDM_TRANSPORT_CONNECTION_CLUSTER=${SDM_CONTROL_CONNECTION_CLUSTER}

export SDM_CLIENT_CONNECTION_URL=${SDM_CONTROL_CONNECTION_URL}